import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import AdminContent from '@/components/admin.content';
import AdminFooter from '@/components/admin.footer';
import AdminHeader from '@/components/admin.header';
import AdminSideBar from '@/components/admin.sidebar';
import { AdminContextProvider } from '@/library/admin.context';
import { SessionProvider } from "next-auth/react"
import { auth } from "@/auth"
const inter = Inter({ subsets: ['vietnamese'] })

export const metadata: Metadata = {
    title: 'Admin dashboard',
    description: 'Generated by create next app',
}

const AdminLayout = async ({ children }: Readonly<{ children: React.ReactNode }>) => {
    const session = await auth()
    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProvider>
                    <AdminContextProvider>
                        <div className='flex h-screen'>
                            <AdminSideBar />
                            <div className='flex flex-col flex-1 w-full'>
                                <AdminHeader session={session} />
                                <AdminContent>
                                    {children}
                                </AdminContent>
                                <AdminFooter />
                            </div>
                        </div>
                    </AdminContextProvider>
                </SessionProvider>
            </body>
        </html>
    )
}

export default AdminLayout